# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- configmap.yaml
- nginx-configmap.yaml

## unified namespace of resources
namespace: sidecar-injector

## unified image name and tag of sidecar-injector image name
images:
- name: sidecar-injector
  newName: quay.io/morvencao/sidecar-injector
  newTag: latest
